### ISSUE TITLE
各方面的功能都不错，很喜欢，建议一个功能

### ISSUE THREAD

**Issue by akkuman** [dtysky/MoeNotes#4]
就是插入图片的功能，可以插入到类似于./images/目录下，每次都手动有点麻烦

**Comment by dtysky** [comment]
@akkuman 

嗯，这个功能我已经考虑并规划到重写里面了，不过实现有些麻烦。因为此软件不是基于数据库，而是基于文件管理，而且目的之一就是可以快速同步到BLOG。
所以图像必须处理云端和本地两种情况，自动上传又可能出现意外状况，下个版本的时候我想想吧www

现在在搞另一个库，所以暂时无法实现。
